name: Build and Upload Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Increase disk space
        uses: fcbg-platforms/increase-disk-space@v0.1.0
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          python3.12 -m pip install --upgrade pip
          python3.12 -m pip install pipenv
          pipenv install requests


      - name: Run release script
        run: ./release.sh

      - name: Upload firmware to GitHub Packages
        run: |
              for firmware in build/*/firmware.bbf; do
                parent_dir=$(basename $(dirname "$firmware"))
                if [ "$parent_dir" = "products" ]; then
                  continue
                fi
                new_name="${parent_dir%%_*}.bbf"
                mv "$firmware" "/tmp/$new_name"
                gh release upload "latest" "/tmp/$new_name" --clobber
              done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
