name: Build and Upload Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps: 
      - name: Increase disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-tags: true
        
      - name: Get latest release tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6
        id: latest_tag
        with: 
          with_initial_version: false

      - name: Check on failures
        if: steps.latest_tag.tag == ''
        run: exit 1

      - name: Download Firmware Signing Key
        env:
          FIRMWARE_SIGNING_KEY: ${{ secrets.FIRMWARE_SIGNING_KEY }} 
        run: echo "$FIRMWARE_SIGNING_KEY" > firmware_signing_key.pem

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          python3.12 -m pip install --upgrade pip
          python3.12 -m pip install pipenv
          pipenv install requests

      - name: Generate firmware of latest build
        run: ./local_build.sh "$TAG" coreone,mk4,xl
        env:
          TAG: $ {{ steps.latest_tag.tag }}

      - name: Upload firmware to GitHub Packages
        run: |
              for firmware in build/*/firmware.bbf; do
                parent_dir=$(basename $(dirname "$firmware"))
                if [ "$parent_dir" = "products" ]; then
                  continue
                fi
                new_name="${parent_dir%%_*}.bbf"
                mv "$firmware" "/tmp/$new_name"
                gh release upload "$TAG" "/tmp/$new_name" --clobber
              done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: $ {{ steps.latest_tag.tag }}
